// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore

// This program generates implementation variants of sorting algorithms.
// Extended with Hybrid Hoare-Lomuto QuickSort from Google's implementation.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"text/template"
)

type Variant struct {
	Name       string
	Path       string
	Package    string
	Imports    string
	FuncSuffix string
	DataType   string
	TypeParam  string
	ExtraParam string
	ExtraArg   string
	Funcs      template.FuncMap
}

var (
	genericVariants = []Variant{
		{
			Name:       "generic_ordered",
			Path:       "zsortordered.go",
			Package:    "slices",
			Imports:    "import \"cmp\"\n",
			FuncSuffix: "Ordered",
			TypeParam:  "[E cmp.Ordered]",
			ExtraParam: "",
			ExtraArg:   "",
			DataType:   "[]E",
			Funcs: template.FuncMap{
				"Less": func(name, i, j string) string {
					return fmt.Sprintf("cmp.Less(%s[%s], %s[%s])", name, i, name, j)
				},
				"Swap": func(name, i, j string) string {
					return fmt.Sprintf("%s[%s], %s[%s] = %s[%s], %s[%s]", name, i, name, j, name, j, name, i)
				},
			},
		},
		{
			Name:       "generic_func",
			Path:       "zsortanyfunc.go",
			Package:    "slices",
			FuncSuffix: "CmpFunc",
			TypeParam:  "[E any]",
			ExtraParam: ", cmp func(a, b E) int",
			ExtraArg:   ", cmp",
			DataType:   "[]E",
			Funcs: template.FuncMap{
				"Less": func(name, i, j string) string {
					return fmt.Sprintf("(cmp(%s[%s], %s[%s]) < 0)", name, i, name, j)
				},
				"Swap": func(name, i, j string) string {
					return fmt.Sprintf("%s[%s], %s[%s] = %s[%s], %s[%s]", name, i, name, j, name, j, name, i)
				},
			},
		},
	}
)

func main() {
	genTest := flag.Bool("test", false, "generate test file instead")
	flag.Parse()

	if *genTest {
		generateTestFile()
		return
	}

	for i := range genericVariants {
		generate(&genericVariants[i])
	}
}

func generate(v *Variant) {
	tmpl, err := template.New("gen").Funcs(v.Funcs).Parse(templateCode)
	if err != nil {
		log.Fatal("template Parse:", err)
	}

	var out bytes.Buffer
	err = tmpl.Execute(&out, v)
	if err != nil {
		log.Fatal("template Execute:", err)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		log.Printf("Warning: format error for %s: %v", v.Path, err)
		formatted = out.Bytes()
	}

	if err := os.WriteFile(v.Path, formatted, 0644); err != nil {
		log.Fatal("WriteFile:", err)
	}
	fmt.Printf("Generated %s\n", v.Path)
}

func generateTestFile() {
	// Generate a simple test file
	testCode := `// Code generated; DO NOT EDIT.
package main

import (
	"fmt"
	"math/rand"
	"sort"
	"time"
)

func main() {
	rand.Seed(time.Now().UnixNano())
	
	sizes := []int{10, 100, 1000, 10000}
	
	for _, n := range sizes {
		// Generate random data
		data := make([]int, n)
		for i := range data {
			data[i] = rand.Intn(n * 10)
		}
		
		// Make copies for comparison
		expected := make([]int, n)
		copy(expected, data)
		sort.Ints(expected)
		
		// Test hybrid sort
		hybridSortOrdered(data, 0, len(data))
		
		// Verify
		ok := true
		for i := range data {
			if data[i] != expected[i] {
				ok = false
				break
			}
		}
		
		if ok {
			fmt.Printf("✓ n=%d: PASS\n", n)
		} else {
			fmt.Printf("✗ n=%d: FAIL\n", n)
		}
	}
}
`
	if err := os.WriteFile("hybrid_test.go", []byte(testCode), 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Generated hybrid_test.go")
}

var templateCode = `// Code generated by gen_sort_variants.go; DO NOT EDIT.

// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package {{.Package}}

{{.Imports}}

// insertionSort{{.FuncSuffix}} sorts data[a:b] using insertion sort.
func insertionSort{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && {{Less "data" "j" "j-1"}}; j-- {
			{{Swap "data" "j" "j-1"}}
		}
	}
}

// ===========================================================================
// Hybrid Hoare-Lomuto QuickSort
// Ported from Google's C++ implementation (Apache 2.0 License)
// 
// Key innovations:
// - Block-based partitioning to reduce branch mispredictions
// - BubbleSort2 processes 2 elements per iteration for small arrays
// - Median-of-three pivot with skew detection for duplicates
// - O(log n) stack depth via tail recursion elimination
// ===========================================================================

const (
	hybridSmallSortThreshold{{.FuncSuffix}} = 16
	hybridBlockSize{{.FuncSuffix}}          = 64
)

// hybridBubbleSort2{{.FuncSuffix}} sorts data[a:b] using an optimized bubble sort.
// Processes two elements at a time, cutting iterations roughly in half.
// The inner loop achieves ~2 cycles with good branch prediction.
func hybridBubbleSort2{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	n := b - a
	if n <= 1 {
		return
	}
	
	// Process array in passes, shrinking by 2 each time
	for size := n; size > 1; size -= 2 {
		// Ensure initial pair is ordered
		if size >= 2 && {{Less "data" "a+1" "a"}} {
			{{Swap "data" "a" "a+1"}}
		}
		
		// Bubble through remaining elements
		for j := 2; j < size; j++ {
			curr := a + j
			prev := a + j - 1
			prev2 := a + j - 2
			
			if {{Less "data" "curr" "prev"}} {
				{{Swap "data" "curr" "prev"}}
				// May need to swap further left
				if j >= 2 && {{Less "data" "prev" "prev2"}} {
					{{Swap "data" "prev" "prev2"}}
				}
			}
		}
	}
	
	// Final cleanup pass for correctness
	for i := a + 1; i < b; i++ {
		for j := i; j > a && {{Less "data" "j" "j-1"}}; j-- {
			{{Swap "data" "j" "j-1"}}
		}
	}
}

// hybridSmallSort{{.FuncSuffix}} efficiently sorts small arrays.
func hybridSmallSort{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	n := b - a
	if n <= 1 {
		return
	}
	if n <= 8 {
		insertionSort{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
		return
	}
	hybridBubbleSort2{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
}

// hybridMedianOfThreeToEnd{{.FuncSuffix}} finds the median of three elements
// and moves it to the end position (b-1) for use as pivot.
func hybridMedianOfThreeToEnd{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	mid := a + (b-a)/2
	last := b - 1
	
	// Sorting network for 3 elements
	if {{Less "data" "mid" "a"}} {
		{{Swap "data" "a" "mid"}}
	}
	if {{Less "data" "last" "a"}} {
		{{Swap "data" "a" "last"}}
	}
	if {{Less "data" "last" "mid"}} {
		{{Swap "data" "mid" "last"}}
	}
	// Median is now at mid; move to end
	{{Swap "data" "mid" "last"}}
}

// hybridHoarePartition{{.FuncSuffix}} partitions data[a:b] with pivot at data[b-1].
// Standard Hoare partition used for moderate-sized arrays.
func hybridHoarePartition{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) int {
	pivot := b - 1
	i := a
	j := pivot - 1
	
	for i <= j {
		// Scan from left for element >= pivot
		for i <= j && {{Less "data" "i" "pivot"}} {
			i++
		}
		// Scan from right for element < pivot
		for i <= j && !{{Less "data" "j" "pivot"}} {
			j--
		}
		if i < j {
			{{Swap "data" "i" "j"}}
			i++
			j--
		}
	}
	// Place pivot in final position
	{{Swap "data" "i" "pivot"}}
	return i
}

// hybridBlockPartition{{.FuncSuffix}} partitions using block-based processing.
// Reduces branch mispredictions by processing elements in blocks.
func hybridBlockPartition{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) int {
	if b-a <= 1 {
		return a
	}
	
	pivot := b - 1
	left := a
	right := pivot - 1
	
	// Block-wise Hoare partition
	for left <= right {
		// Process block from left: move elements < pivot to their position
		blockEnd := left + hybridBlockSize{{.FuncSuffix}}
		if blockEnd > right+1 {
			blockEnd = right + 1
		}
		
		writePos := left
		for readPos := left; readPos < blockEnd; readPos++ {
			if {{Less "data" "readPos" "pivot"}} {
				if readPos != writePos {
					{{Swap "data" "readPos" "writePos"}}
				}
				writePos++
			}
		}
		
		// Process block from right: move elements >= pivot to their position
		blockStart := right - hybridBlockSize{{.FuncSuffix}} + 1
		if blockStart < writePos {
			blockStart = writePos
		}
		
		writeEnd := right
		for readPos := right; readPos >= blockStart; readPos-- {
			if !{{Less "data" "readPos" "pivot"}} {
				if readPos != writeEnd {
					{{Swap "data" "readPos" "writeEnd"}}
				}
				writeEnd--
			}
		}
		
		// Update boundaries for next iteration
		left = writePos
		right = writeEnd
		
		// Exchange remaining misplaced elements
		for left < right {
			for left < right && {{Less "data" "left" "pivot"}} {
				left++
			}
			for left < right && !{{Less "data" "right" "pivot"}} {
				right--
			}
			if left < right {
				{{Swap "data" "left" "right"}}
				left++
				right--
			}
		}
	}
	
	// Place pivot in final position
	{{Swap "data" "left" "pivot"}}
	return left
}

// hybridChoosePivotAndPartition{{.FuncSuffix}} selects pivot and partitions.
// Returns (pivotPos, equalEnd) where equalEnd > pivotPos indicates
// duplicate elements that were consolidated.
func hybridChoosePivotAndPartition{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) (int, int) {
	hybridMedianOfThreeToEnd{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
	
	// Choose partition strategy based on size
	var p int
	if b-a > hybridBlockSize{{.FuncSuffix}}*2 {
		p = hybridBlockPartition{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
	} else {
		p = hybridHoarePartition{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
	}
	
	n := b - a
	m := p - a
	
	// Skew detection: very unbalanced partition may indicate duplicates
	if m < n/8 {
		// Consolidate elements equal to pivot
		eq := p
		for i := p + 1; i < b; i++ {
			// Check if data[i] == data[p]
			if !{{Less "data" "p" "i"}} && !{{Less "data" "i" "p"}} {
				eq++
				if i != eq {
					{{Swap "data" "i" "eq"}}
				}
			}
		}
		if eq > p {
			return p, eq + 1
		}
	}
	return p, p
}

// hybridQuickSortImpl{{.FuncSuffix}} is the main sorting implementation.
func hybridQuickSortImpl{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	for b-a > hybridSmallSortThreshold{{.FuncSuffix}} {
		p, pEnd := hybridChoosePivotAndPartition{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
		
		nleft := p - a
		nright := b - pEnd
		
		// Recurse on smaller partition for O(log n) stack depth
		if nleft <= nright {
			hybridQuickSortImpl{{.FuncSuffix}}(data, a, p {{.ExtraArg}})
			a = pEnd
		} else {
			hybridQuickSortImpl{{.FuncSuffix}}(data, pEnd, b {{.ExtraArg}})
			b = p
		}
	}
	hybridSmallSort{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
}

// hybridSort{{.FuncSuffix}} sorts data[a:b] using hybrid Hoare-Lomuto quicksort.
func hybridSort{{.FuncSuffix}}{{.TypeParam}}(data {{.DataType}}, a, b int {{.ExtraParam}}) {
	if b-a <= 1 {
		return
	}
	hybridQuickSortImpl{{.FuncSuffix}}(data, a, b {{.ExtraArg}})
}
`